version: 2

models:
  - name: sem_revenue_metrics
    description: >
      Business-friendly revenue view for BI tools. Grain: one row per order.
      Exposes gross revenue, net revenue, gross profit, and FX-adjusted amounts.
    columns:
      - name: "Order ID"
        # tests:
        #   - unique
        #   - not_null

  - name: sem_customer_kpis
    description: >
      Customer KPI view for dashboards. Grain: one row per customer.
      Exposes RFM status, CLV band, and lifetime revenue metrics.
    columns:
      - name: "Customer ID"
        # tests:
        #   - unique
        #   - not_null
