version: 2

models:
  - name: stg_orders
    description: "Cleaned and typed orders from raw source. One row per order."
    columns:
      - name: order_id
        description: "Unique order identifier"
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: order_amount_usd
        tests:
          - not_null
      - name: order_status
        # tests:
        #   - accepted_values:
        #       values: ['completed', 'cancelled', 'returned', 'pending']

  - name: stg_customers
    description: "Cleaned customer records. Contains PII — restricted access."
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - unique
          - not_null
      - name: customer_segment
        # tests:
        #   - accepted_values:
        #       values: ['premium', 'standard', 'trial']

  - name: stg_products
    description: "Product catalog with pricing and margin info."
    columns:
      - name: product_id
        description: "Unique product identifier"
        tests:
          - unique
          - not_null
      - name: list_price_usd
        tests:
          - not_null
